#!/usr/bin/env node

const path = require('path')

module.exports = {
  'config': path.resolve('src', 'Config/config.ts'),
  'models-path': path.resolve('src', 'Models'),
  'seeders-source-path': path.resolve('src', 'Database', 'Seeders'),
  'seeders-compiled-path': path.resolve('dist', 'Database', 'Seeders'),
  'migrations-source-path': path.resolve('src', 'Database', 'Migrations'),
  'migrations-compiled-path': path.resolve('dist', 'Database', 'Migrations')
}
